hwi_oauth:
    # https://github.com/hwi/HWIOAuthBundle/blob/master/docs/2-configuring_resource_owners.md
    resource_owners:
        auth0:
            type:           auth0
            client_id:      '%env(AUTH0_CLIENT_ID)%'
            client_secret:  '%env(AUTH0_CLIENT_SECRET)%'
            base_url:       "https://%env(AUTH0_DOMAIN)%"
            scope:          "openid profile email"

        facebook:
            type:                facebook
            client_id:           '%env(FB_ID)%'
            client_secret:       '%env(FB_SECRET)%'
            scope:               "email"
            options:
                csrf: true
                refresh_on_expire: true
                display: popup
                auth_type: rerequest

        github:
            type: github
            client_id: '%env(GITHUB_CLIENT_ID)%'
            client_secret: '%env(GITHUB_CLIENT_SECRET)%'
            scope: 'user:email'

        gitlab:
            type: gitlab
            client_id: '%env(GITLAB_CLIENT_ID)%'
            client_secret: '%env(GITLAB_CLIENT_SECRET)%'
            scope: 'email'

        google:
            type:                google
            client_id:           '%env(GOOGLE_ID)%'
            client_secret:       '%env(GOOGLE_SECRET)%'
            scope:               "email profile"
        
        instagram:
            type:           instagram
            client_id:      '%env(INSTAGRAM_CLIENT_ID)%'
            client_secret:  '%env(INSTAGRAM_CLIENT_SECRET)%'
            scope: "basic"
        
        linkedin:
            type:           linkedin
            client_id:     '%env(LINKEDIN_CLIENT_ID)%'
            client_secret:  '%env(LINKEDIN_CLIENT_SECRET)%'
            scope: "r_emailaddress"

        sensio:
            type:                sensio_connect
            client_id:           '%env(SYMFONY_CONNECT_ID)%'
            client_secret:       '%env(SYMFONY_CONNECT_SECRET)%'
            scope:               "SCOPE_PUBLIC"

        twitter:
            type: twitter
            client_id: '%env(TWITTER_CLIENT_ID)%'
            client_secret: '%env(TWITTER_SECRET)%'
            options:
                include_email: true