#index:
#    path: /
#    controller: App\Controller\DefaultController::index

#fos_user:
#    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
#
#fos_user_profile:
#    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
#    prefix: /profile
#
#fos_user_register:
#    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
#    prefix: /register
#
#fos_user_resetting:
#    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
#    prefix: /resetting
#
#fos_user_change_password:
#    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
#    prefix: /profile
controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.php"
    prefix:   /connect

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.php"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.php"
    prefix:   /login

facebook_login:
    path: /login/check-facebook

google_login:
    path: /login/check-google

twitter_login:
    path: /login/check-twitter

sensio_connect_login:
    path: /login/check-sensio

github_login:
    path: /login/check-github

gitlab_login:
    path: /login/check-gitlab

linkedin_login:
    path: /login/check-linkedin

# bitbucket_login:
#     path: /login/check-bucket

instagram_login:
    path: /login/check-instagram

auth0_login:
    path:    /auth0/callback

auth0_logout:
    path: /auth0/logout